Alura.WebAPI.WebApp/Models/HomeViewModel.cs
using Alura.ListaLeitura.Modelos;
using System.Collections.Generic;

namespace Alura.ListaLeitura.WebApp.Models
{
    public class HomeViewModel
    {
        public IEnumerable<LivroApi> ParaLer { get; set; }
        public IEnumerable<LivroApi> Lendo { get; set; }
        public IEnumerable<LivroApi> Lidos { get; set; }
    }
}

Alura.WebAPI.WebApp/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Alura.ListaLeitura.WebApp.Models
{
    public class RegisterViewModel
    {
        [Required]
        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmação de senha")]
        [Compare("Password", ErrorMessage = "Senha e confirmação são diferentes.")]
        public string ConfirmPassword { get; set; }
    }
}

Alura.WebAPI.WebApp/Controllers/HomeController.cs
using Alura.ListaLeitura.Modelos;
using Alura.ListaLeitura.WebApp.Models;
using Alura.ListaLeitura.HttpClients;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Alura.ListaLeitura.WebApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly LivroApiClient _api;

        public HomeController(LivroApiClient api)
        {
            _api = api;
        }

        private async Task<IEnumerable<LivroApi>> ListaDoTipo(TipoListaLeitura tipo)
        {
            var lista = await _api.GetListaLeituraAsync(tipo);
            return lista.Livros;
        }

        public async Task<IActionResult> Index()
        {
            var model = new HomeViewModel
            {
                ParaLer = await ListaDoTipo(TipoListaLeitura.ParaLer),
                Lendo = await ListaDoTipo(TipoListaLeitura.Lendo),
                Lidos = await ListaDoTipo(TipoListaLeitura.Lidos)
            };
            return View(model);
        }
    }
}

Alura.WebAPI.WebApp/Controllers/LivroController.cs
using Alura.ListaLeitura.Modelos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Alura.ListaLeitura.HttpClients;

namespace Alura.ListaLeitura.WebApp.Controllers
{
    [Authorize]
    public class LivroController : Controller
    {
        private readonly LivroApiClient _api;

        public LivroController(LivroApiClient api)
        {
            _api = api;
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View(new LivroUpload());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo(LivroUpload model)
        {
            if (ModelState.IsValid)
            {
                await _api.PostLivroAsync(model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ImagemCapa(int id)
        {
            byte[] img = await _api.GetCapaLivroAsync(id);
            if (img != null)
            {
                return File(img, "image/png");
            }
            return File("~/images/capas/capa-vazia.png", "image/png");
        }

        [HttpGet]
        public async Task<IActionResult> Detalhes(int id)
        {
            var model = await _api.GetLivroAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model.ToUpload());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Detalhes(LivroUpload model)
        {
            if (ModelState.IsValid)
            {
                await _api.PutLivroAsync(model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Remover(int id)
        {
            var model = await _api.GetLivroAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            await _api.DeleteLivroAsync(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

Alura.WebAPI.WebApp/Controllers/UsuarioController.cs
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Threading.Tasks;
using Alura.ListaLeitura.Seguranca;
using Alura.ListaLeitura.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace Alura.ListaLeitura.WebApp.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UserManager<Usuario> _userManager;
        private readonly SignInManager<Usuario> _signInManager;

        public UsuarioController(UserManager<Usuario> userManager, SignInManager<Usuario> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login()
        {
            await _signInManager.SignOutAsync();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Login, model.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(String.Empty, "Erro na autenticação");
                return View(model);
            }
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new Usuario { UserName = model.Login };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

    }
}

Alura.WebAPI.WebApp/Views/Home/Index.cshtml
@model HomeViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>
    <a asp-action="Novo" asp-controller="Livro" id="novo-flutuante" >
        <p class="plus">+</p>
    </a>

    <div class="row">
        <div class="card col-md-6 col-lg-3 lista-leitura" id="coluna-paraler" data-id="paraler">
            <h4 class="card-header">Para Ler</h4>
            <ul class="">
                @foreach (var livro in Model.ParaLer)
                {
                    <partial name="~/Views/Shared/Livro.cshtml" model="livro" />
                }
            </ul>
        </div>
        <!--fim #coluna-paraler-->

        <div class="card col-md-6 col-lg-3 lista-leitura" id="coluna-lendo" data-id="lendo">
            <h4 class="card-header">Lendo</h4>
            <ul class="list-group">
                @foreach (var livro in Model.Lendo)
                {
                    <partial name="~/Views/Shared/Livro.cshtml" model="livro" />
                }
            </ul>
        </div>
        <!--fim #coluna-lendo-->

        <div class="card col-md-6 col-lg-3 lista-leitura" id="coluna-lidos" data-id="lidos">
            <h4 class="card-header">Lidos</h4>
            <ul class="">
                @foreach (var livro in Model.Lidos)
                {
                    <partial name="~/Views/Shared/Livro.cshtml" model="livro" />
                }
            </ul>
        </div>
        <!--fim #coluna-lidos-->
    </div>



</main>

Alura.WebAPI.WebApp/Views/Livro/Detalhes.cshtml
@model LivroUpload

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>

    <form class="row" role="form" enctype="multipart/form-data" asp-action="Detalhes" method="post">

        <input type="hidden" asp-for="Id" />

        <div class="col-5 text-center">
            <div class="capa">
                <img class="livro img-fluid"
                     id="imgCapa"
                     src="/Livro/ImagemCapa/@Model.Id"
                     alt="@Model.Titulo"
                     data-id="@Model.Id" />

                <p class="py-3">
                    <label class="btn btn-outline-dark">
                        Alterar Capa
                        <input id="ImagemCapa" asp-for="@Model.Capa" type="file" class="d-none" accept="image/x-png" />
                    </label>
                </p>
            </div>
        </div>

        <div class="col-5">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Subtitulo" class="control-label"></label>
                <input asp-for="Subtitulo" class="form-control" />
                <span asp-validation-for="Subtitulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Resumo" class="control-label"></label>
                <textarea asp-for="Resumo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Resumo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Lista" class="control-label"></label>
                <select asp-for="Lista" class="form-control">
                    @foreach (var tipo in Enum.GetValues(typeof(TipoListaLeitura)))
                    {
                        <option value="@tipo">@tipo</option>
                    }
                </select>
                <span asp-validation-for="Capa" class="text-danger"></span>
            </div>

            <footer class="form-group">
                <button class="btn btn-outline-success">GRAVAR</button>
                <button id="btnExcluir" class="btn btn-outline-danger">EXCLUIR</button>
            </footer>
        </div>

    </form>

</main>

@section Scripts{
    <script>
        $(function () {
            $('#btnExcluir').click(function () {
                $('form').attr('action', '/Livro/Remover');
                $('form').submit();
            });
            $('#ImagemCapa').change(function () {
                var input = this;
                var url = $(this).val();
                var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                if (input.files && input.files[0] && (ext === "png")) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        console.log("chegou aqui!");
                        $('#imgCapa').attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
                else {
                    $('#imgCapa').attr('src', '~/images/capas/capa-vazia.png');
                }
            });
        });
    </script>
}

Alura.WebAPI.WebApp/Views/Livro/Novo.cshtml
@model LivroUpload

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Novo Livro</h2>

<main>

    <form class="row" role="form" enctype="multipart/form-data" asp-action="Novo" method="post">

        <div class="col-5 text-center">
            <div class="capa">
                <img class="livro img-fluid"
                     id="imgCapa"
                     src="~/images/capas/capa-vazia.png"
                     alt="@Model.Titulo"
                     data-id="@Model.Id" />
                <p class="py-3">
                    <label class="btn btn-outline-dark">
                        Alterar Capa
                        <input id="ImagemCapa" name="Capa" type="file" class="d-none" accept="image/x-png" />
                    </label>
                </p>
            </div>
        </div>

        <div class="col-5">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Subtitulo" class="control-label"></label>
                <input asp-for="Subtitulo" class="form-control" />
                <span asp-validation-for="Subtitulo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Resumo" class="control-label"></label>
                <textarea asp-for="Resumo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Resumo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Lista" class="control-label"></label>
                <select asp-for="Lista" class="form-control">
                    @foreach (var tipo in Enum.GetValues(typeof(TipoListaLeitura)))
                    {
                        <option value="@tipo">@tipo</option>
                    }
                </select>
                <span asp-validation-for="Lista" class="text-danger"></span>
            </div>

            <footer class="form-group">
                <button class="btn btn-outline-success">GRAVAR</button>
            </footer>
        </div>

    </form>

</main>

@section Scripts{
    <script>
        $(function () {
            $('#ImagemCapa').change(function () {
                console.log("chegou aqui!");
                var input = this;
                var url = $(this).val();
                var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
                if (input.files && input.files[0] && (ext == "png")) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#imgCapa').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
                else {
                    $('#imgCapa').attr('src', '~/images/capas/capa-vazia.png');
                }
            });
        });
    </script>
}

Alura.WebAPI.WebApp/Views/Shared/Livro.cshtml
@model LivroApi

<li class="list-group-item my-3 mx-5 border-0">
    <a asp-action="Detalhes" asp-controller="Livro" asp-route-id="@Model.Id">
        <img class="livro img-fluid" src="/Livro/ImagemCapa/@Model.Id" alt="@Model.Titulo" data-id="@Model.Id">
    </a>
</li>

Alura.WebAPI.WebApp/Views/Shared/NovoLivro.cshtml
<li class="list-group-item my-3 mx-5 border-0">
    <a asp-action="Novo" asp-controller="Livro">
        <img class="novo-livro img-fluid" src="~/images/livro-novo.png" alt="Incluir Livro">
    </a>
</li>

Alura.WebAPI.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lista de Leitura</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/estilo.css" />
</head>
<body class="d-flex flex-column" style="min-height: 100vh">

    <nav class="nav navbar bg-dark fixed-top">
        <a asp-action="Index" asp-controller="Home" class="navbar-brand">
            <img src="~/images/logo.png" alt="Lista de Leitura - Casa do Código">
        </a>
    </nav>

    <div class="container-fluid flex-grow-1">
        @RenderBody()
    </div>

    <footer class="bg-dark text-center text-white">
        <p class="my-0">Casa do Código &copy; 2018</p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-ui/dist/jquery-ui.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Alura.WebAPI.WebApp/Views/Usuario/Login.cshtml
@model LoginModel

@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<main>

    <form asp-action="Login" method="post">

        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <h2>Login</h2>
            </div>
            <div class="col-2"></div>
        </div>

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>

        <div class="row">
            <div class="col-2"></div>
            <div class="form-group col-4">
                <label asp-for="Login"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>

            <div class="form-group col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="col-2"></div>
        </div>

        <footer class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <button class="btn btn-primary">LOGIN</button>
            </div>
        </footer>

    </form>

</main>

Alura.WebAPI.WebApp/Views/Usuario/Register.cshtml
@model RegisterViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>


    <form method="post">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <h2>Registro</h2>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="form-group col-8">
                <label asp-for="Login"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="form-group col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="col-2"></div>
        </div>
        <footer class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <button type="submit" class="btn btn-primary">REGISTRO</button>
            </div>
            <div class="col-2"></div>
        </footer>
    </form>

</main>